name: backend

env:
  BACKEND_ROOT: ./backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ${{env.BACKEND_ROOT}}/go.mod
        cache-dependency-path: ${{env.BACKEND_ROOT}}/go.sum

    - name: Build
      run: go build -v ./...

    - name: Store binaries
      uses: actions/upload-artifact@v4
      with:
        name: backend-binaries
        path: ${{env.BACKEND_ROOT}}/bin
        retention-days: 7

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ${{env.BACKEND_ROOT}}/go.mod
        cache-dependency-path: ${{env.BACKEND_ROOT}}/go.sum

    - name: Set up gotestfmt
      run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

    - name: Test
      working-directory: ${{env.SERVER_ROOT}}
      run: go test -json -v ./... | gotestfmt -hide "empty-packages"
